export const navbarData = [
  { id: 1, title: "Laptops" },
  { id: 2, title: "Desktop PCs" },
  { id: 3, title: "Networking Devices" },
  { id: 4, title: "Printers & Scanners" },
  { id: 5, title: "PC Parts" },
  { id: 6, title: "All Other Products" },
  { id: 7, title: "Repairs" },
];

export const navbarBasketData = [
  {
    id: 1,
    group: "msi",
    img: "./images/pc.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-03AU 15.6 MULTITOUCH All-In-On...",
    count: 1,
    price: 310,
  },
  {
    id: 2,
    group: "msi",
    img: "./images/pc.png",
    title: "HP PC : MSI Pro 16 Flex-36AU 15.6 MULTITOUCH All-In-On...",
    count: 1,
    price: 540,
  },
];

export const products = [
  {
    id: 1,
    group: "HP",
    status: true,
    desk: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULITOUCH All-In-On...",
    oldPrice: 540,
    price: 520,
    img: "./images/product/product1.png",
    starRating: 4,
  },
  {
    id: 2,
    group: "Lenovo",
    status: false,
    desk: "EX DISPLAY : MSI ro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldPrice: 800,
    price: 769,
    img: "./images/product/product2.png",
    starRating: 5,
  },
  {
    id: 3,
    group: "Lenovo",
    status: true,
    desk: "EX DISPLA : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldPrice: 950,
    price: 850,
    img: "./images/product/product3.png",
    starRating: 3,
  },
  {
    id: 4,
    group: "msi",
    status: true,
    desk: "EX DISPLAY : MSI Pro 16 Flex-03AU 159.6 MULTITOUCH All-In-On...",
    oldPrice: 599,
    price: 500,
    img: "./images/product/product4.png",
    starRating: 2,
  },
  {
    id: 5,
    group: "HP",
    status: false,
    desk: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH Al-In-On...",
    oldPrice: 300,
    price: 250,
    img: "./images/product/product5.png",
    starRating: 1,
  },
  {
    id: 6,
    group: "msi",
    status: true,
    desk: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6MULTITOUCH All-In-On...",
    oldPrice: 490,
    price: 300,
    img: "./images/product/product6.png",
    starRating: 5,
  },
  {
    id: 7,
    group: "HP",
    status: false,
    desk: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 LTITOUCH All-I-On...",
    oldPrice: 499,
    price: 400,
    img: "./images/product/product7.png",
    starRating: 5,
  },
  {
    id: 8,
    group: "Lenovo",
    status: true,
    desk: "EX DISY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldPrice: 600,
    price: 350,
    img: "./images/product/product8.png",
    starRating: 3,
  },
  {
    id: 9,
    group: "HP",
    status: true,
    desk: "EX DISPLAY : MSI Pro 16 Flex-03615.6 MULTITOUCH All-In-On...",
    oldPrice: 500,
    price: 400,
    img: "./images/product/product9.png",
    starRating: 4,
  },
  {
    id: 10,
    group: "HP",
    status: false,
    desk: "EX DISPLAY MSI Pro 16 Flex-03615.6 MULTOUCH All-In-On...",
    oldPrice: 600,
    price: 450,
    img: "./images/product/product4.png",
    starRating: 5,
  },
];

export const usersComments = [
  {
    id: 1,
    name: "Mohammad",
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet, reprehenderit vel perferendis alias nesciunt ducimus rem earum excepturi. Corrupti vel laboriosam quibusdam impedit quas facilis nisi delectus, voluptate aspernatur recusandae..",
  },
  {
    id: 2,
    name: "Reza",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores ea voluptates blanditiis autem, accusamus corporis aut. Eius, voluptatibus, dolor facilis ratione minima impedit numquam sequi repellendus ex ea dolore voluptates.",
  },
  {
    id: 3,
    name: "Sara",
    text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet, reprehenderit vel perferendis alias nesciunt ducimus rem earum excepturi. Corrupti vel laboriosam quibusdam impedit quas facilis nisi delectus, voluptate aspernatur recusandae..",
  },
];
